fixing crash when watching a directory... (#1273)
When a file changed in a watched directory the following exception occurred

  File "crossbar/controller/process.py", line 849, in on_filesystem_change
    self._node._reactor.callLater(worker.watch_timeout, self.start_guest, worker_id, worker_config, details)
builtins.AttributeError: 'NodeControllerSession' object has no attribute 'start_guest'

It seems like there was an api name change and this one call got missed.